# Generated by Django 5.1 on 2024-09-14 08:34

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('date_received', models.DateField(auto_created=datetime.datetime(2024, 9, 14, 8, 34, 4, 844178, tzinfo=datetime.timezone.utc))),
                ('ordered_time', models.DateField(auto_created=datetime.datetime(2024, 9, 14, 8, 34, 4, 844178, tzinfo=datetime.timezone.utc))),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True, null=True)),
                ('shipment_value', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('client', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
