# Generated by Django 5.1.1 on 2024-09-15 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_delete_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_received',
            field=models.DateField(auto_created=datetime.datetime(2024, 9, 15, 9, 8, 38, 50690, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateField(auto_created=datetime.datetime(2024, 9, 15, 9, 8, 38, 50690, tzinfo=datetime.timezone.utc)),
        ),
    ]
