# Generated by Django 5.1.1 on 2024-09-15 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_date_received_alter_order_ordered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_received',
            field=models.DateField(auto_created=datetime.datetime(2024, 9, 15, 9, 27, 32, 850664, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
