# Generated by Django 5.1.1 on 2024-09-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_shop_alter_order_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledpackages',
            name='date_cancelled',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentpackages',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
