# Generated by Django 5.1.1 on 2024-09-27 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cancelledpackages_date_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledpackages',
            name='date_cancelled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sentpackages',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
