# Generated by Django 5.1.1 on 2024-09-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cancelledpackages_date_cancelled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelledpackages',
            old_name='order_time',
            new_name='ordered_time',
        ),
        migrations.RenameField(
            model_name='sentpackages',
            old_name='order_time',
            new_name='ordered_time',
        ),
    ]
